In [1]:
import numpy as np

In [8]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
b=np.random.randn(12)
print(b)

[ 1.37608084 -0.37778764 -2.57544118  1.15908946 -0.75876025  1.98056814
 -0.39169872 -0.46806208  0.70343408 -1.66667455  1.55703222  0.98186732]


In [13]:
b=np.random.randn(3,4)
print(b)

[[-1.59347474 -0.62760315 -1.11026925 -0.65163932]
 [-0.09428731 -0.31822435  0.09088261 -1.44094995]
 [-0.13594423  0.16269835 -0.80552164  0.02954196]]


In [16]:
c=b*10
print(c)

[[-15.93474745  -6.27603146 -11.10269253  -6.51639324]
 [ -0.94287313  -3.18224346   0.90882613 -14.40949954]
 [ -1.3594423    1.6269835   -8.05521641   0.29541961]]


In [18]:
c+c

array([[-31.86949489, -12.55206293, -22.20538507, -13.03278648],
       [ -1.88574625,  -6.36448692,   1.81765226, -28.81899909],
       [ -2.7188846 ,   3.253967  , -16.11043282,   0.59083921]])

In [19]:
c.dtype

dtype('float64')

In [20]:
c.shape

(3, 4)

In [21]:
g=[5,4,3,2,2]

In [22]:
t=np.array(g)

In [24]:
print(g)
print(t)
t

[5, 4, 3, 2, 2]
[5 4 3 2 2]


array([5, 4, 3, 2, 2])

In [25]:
dd=[[1,2,233,4],[2,3,4]]

In [26]:
ff=np.array(dd)

In [27]:
ff

array([list([1, 2, 233, 4]), list([2, 3, 4])], dtype=object)

In [28]:
d=[[1,2,233,4],[2,3,4,4]]

In [29]:
f=np.array(d)

In [30]:
f

array([[  1,   2, 233,   4],
       [  2,   3,   4,   4]])

In [31]:
ff.ndim

1

In [32]:
f.ndim

2

In [33]:
ff.shape

(2,)

In [34]:
f.shape

(2, 4)

In [35]:
ff.dtype

dtype('O')

In [36]:
f.dtype

dtype('int32')

In [37]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.empty((2,3))

array([[2.87e-322, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [42]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [43]:
print(arr1)
print(arr2)

[1. 2. 3.]
[1 2 3]
