In [1]:
import numpy as np

In [8]:
a=np.array(["a,b",4,5,67,3,'g'])
print(type(a))
print(a)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.dtype.name)

<class 'numpy.ndarray'>
['a,b' '4' '5' '67' '3' 'g']
1
6
(6,)
<U3
str96


In [9]:
b=np.array(5.4)
print(type(b))
print(b)
print(b.ndim)
print(b.size)
print(b.shape)
print(b.dtype)
print(b.dtype.name)

<class 'numpy.ndarray'>
5.4
0
1
()
float64
float64


In [12]:
c=np.array(True,False)
print(type(b))
print(b)
print(b.ndim)
print(b.size)
print(b.shape)
print(b.dtype)
print(b.dtype.name)

TypeError: data type not understood

In [18]:
c=np.array([True,False])
print(type(c))
print(c)
print(c.ndim)
print(c.size)
print(c.shape)
print(c.dtype)
print(c.dtype.name)

<class 'numpy.ndarray'>
[ True False]
1
2
(2,)
bool
bool


In [20]:
d=np.array([1,2,3],[6,"y",7],[9,0,0.999988])
print(type(d))
print(d)
print(d.ndim)
print(d.size)
print(d.shape)
print(d.dtype)
print(d.dtype.name)

ValueError: only 2 non-keyword arguments accepted

In [21]:
d=np.array([[1,2,3],[6,"y",7],[9,0,0.999988]])
print(type(d))
print(d)
print(d.ndim)
print(d.size)
print(d.shape)
print(d.dtype)
print(d.dtype.name)

<class 'numpy.ndarray'>
[['1' '2' '3']
 ['6' 'y' '7']
 ['9' '0' '0.999988']]
2
9
(3, 3)
<U11
str352


In [23]:
d=np.array([[1,4,2,3],[6,"y",7],[9,0,0.999988]])
print(type(d))
print(d)
print(d.ndim)
print(d.size)
print(d.shape)
print(d.dtype)
print(d.dtype.name)

<class 'numpy.ndarray'>
[list([1, 4, 2, 3]) list([6, 'y', 7]) list([9, 0, 0.999988])]
1
3
(3,)
object
object


In [24]:
e=np.array([[1,2,3]])
print(type(e))
print(e)
print(e.ndim)
print(e.size)
print(e.shape)
print(e.dtype)
print(e.dtype.name)

<class 'numpy.ndarray'>
[[1 2 3]]
2
3
(1, 3)
int32
int32


In [26]:
f=np.array(["5.6","6",4,6,"7"])
f1=f.astype(int)

ValueError: invalid literal for int() with base 10: '5.6'

In [28]:
f=np.array(["5","6",4,6,"7"])
f1=f.astype(int)
f1

array([5, 6, 4, 6, 7])

In [30]:
g=np.array([876,98,8,87,76,7])
g.astype("int8")

array([108,  98,   8,  87,  76,   7], dtype=int8)

In [31]:
g=np.array([876,98,8,87,76,7])
g.astype("int16")

array([876,  98,   8,  87,  76,   7], dtype=int16)

In [32]:
g=np.array([876,98,8,87,76,7])
g.astype("int4")

TypeError: data type "int4" not understood

In [34]:
h=np.ones(6)
h

array([1., 1., 1., 1., 1., 1.])

In [36]:
i=np.ones((4,9))
i

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
np.zeros((2,6,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [40]:
np.zeros((6,5),dtype=str)

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [41]:
np.zeros((5,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [42]:
np.empty(4)

array([2.211504e-316, 0.000000e+000, 0.000000e+000, 0.000000e+000])

In [43]:
np.empty((5,4))

array([[2.56443242e-316, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000],
       [2.56761491e-312, 5.30276956e+180, 1.57076922e-076,
        4.57664832e-071],
       [4.06333708e-086, 3.35810571e-143, 6.01433264e+175,
        6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180, 1.88832290e+185,
        1.10951806e-047],
       [4.08088293e+179, 1.25904334e-075, 7.75356633e-144,
        1.50008929e+248]])

In [47]:
np.full(4,6)

array([6, 6, 6, 6])

In [50]:
np.full((5,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [53]:
np.full((9,0),0.9)

array([], shape=(9, 0), dtype=float64)

In [54]:
np.full((9,1),10)

array([[10],
       [10],
       [10],
       [10],
       [10],
       [10],
       [10],
       [10],
       [10]])

In [55]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
np.eye((5,4))

TypeError: 'tuple' object cannot be interpreted as an integer

In [57]:
np.arange(2,87,7)

array([ 2,  9, 16, 23, 30, 37, 44, 51, 58, 65, 72, 79, 86])

In [62]:
j=np.linspace(2,87,6)
j

array([ 2., 19., 36., 53., 70., 87.])

In [63]:
j.reshape(3,2)

array([[ 2., 19.],
       [36., 53.],
       [70., 87.]])

In [70]:
print(j.ravel())
j.ravel

[ 2. 19. 36. 53. 70. 87.]


<function ndarray.ravel>

In [68]:
print(j.flatten)
print(j.ravel)
j.flatten

<built-in method flatten of numpy.ndarray object at 0x000000000551FD50>
<built-in method ravel of numpy.ndarray object at 0x000000000551FD50>


<function ndarray.flatten>

In [69]:
j.flatten()

array([ 2., 19., 36., 53., 70., 87.])

In [82]:
j=j.reshape((3,2))
j

array([[ 2., 19.],
       [36., 53.],
       [70., 87.]])

In [83]:
print(j)
print(j.transpose())

[[ 2. 19.]
 [36. 53.]
 [70. 87.]]
[[ 2. 36. 70.]
 [19. 53. 87.]]


In [84]:
print(j)
print(j.T)

[[ 2. 19.]
 [36. 53.]
 [70. 87.]]
[[ 2. 36. 70.]
 [19. 53. 87.]]


In [85]:
k=j.T
print(k)

[[ 2. 36. 70.]
 [19. 53. 87.]]


In [87]:
np.append(5,6,8,9)

TypeError: append() takes from 2 to 3 positional arguments but 4 were given

In [88]:
np.append(4,5)

array([4, 5])

In [90]:
np.append(k,4,5)

AxisError: axis 5 is out of bounds for array of dimension 2

In [91]:
np.append(k,8)

array([ 2., 36., 70., 19., 53., 87.,  8.])

In [96]:
np.delete(k,[2])#2 is the index

array([ 2., 36., 19., 53., 87.])

In [97]:
np.insert(k,7,78,98,8)

TypeError: insert() takes from 3 to 4 positional arguments but 5 were given

In [98]:
np.insert(k,8,87,76)

AxisError: axis 76 is out of bounds for array of dimension 2

In [100]:
np.insert(k,1,5)#1 is index and 5 is value to be inserted

array([ 2.,  5., 36., 70., 19., 53., 87.])

In [101]:
np.array_equal(k,j)

False

In [102]:
k.append(88)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [103]:
k.resize()

In [104]:
k

array([[ 2., 36., 70.],
       [19., 53., 87.]])

In [107]:
k.resize()
k=k.T
k

array([[ 2., 19.],
       [36., 53.],
       [70., 87.]])

In [108]:
k.resize()
k

array([[ 2., 19.],
       [36., 53.],
       [70., 87.]])