Numpy vs Python List

In [1]:
l=range(1200000)#python list

In [2]:
import numpy as np

In [3]:
a=np.arange(1200000)#a numpy array

In [4]:
%time for w in range(1,15): t=[x*2 for x in l]

Wall time: 5.16 s


In [5]:
%time for w in range(1,15): h=a*2

Wall time: 146 ms


A Multidimensional Array Object

In [6]:
import numpy as np

In [7]:
a=np.zeros((4,3))#attributes of numpy

In [8]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.empty((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.empty((4,5))

array([[2.26978382e-316, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 5.07929180e-299],
       [5.30276956e+180, 1.57076922e-076, 4.57399183e-071,
        3.65961324e-086, 3.35959363e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 7.16798118e-038],
       [4.08779587e-037, 1.08414616e-042, 2.65057896e-052,
        5.43905131e-143, 1.50008929e+248]])

In [21]:
e=[3,4,5,5,65]

In [22]:
np.array(e)

array([ 3,  4,  5,  5, 65])

In [29]:
q=np.arange(3,30,3)

In [30]:
q.shape

(9,)

In [32]:
q.reshape((3,3))

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [33]:
q.reshape((3,3,1))

array([[[ 3],
        [ 6],
        [ 9]],

       [[12],
        [15],
        [18]],

       [[21],
        [24],
        [27]]])

In [34]:
q.reshape((3,3)).shape

(3, 3)

In [35]:
q.dtype

dtype('int32')

In [36]:
q.ndim

1

In [37]:
q.reshape((3,3,1)).ndim

3

In [22]:
import numpy as np

In [23]:
a=np.random.randn((10))

In [24]:
b=np.random.randn((10))

In [25]:
a

array([-1.66690132, -0.88630067, -1.3333805 , -0.60245125, -0.41875169,
        2.62081855,  0.27429575,  0.04475403,  0.1799557 , -0.4460485 ])

In [26]:
b

array([-0.30174233, -1.60595985,  0.24989113,  0.64272354, -2.78134898,
       -0.84759336, -0.72859829, -0.01060969,  1.17167092,  0.13403804])

In [27]:
a+b

array([-1.96864365, -2.49226053, -1.08348937,  0.04027229, -3.20010067,
        1.77322519, -0.45430254,  0.03414435,  1.35162662, -0.31201045])

In [28]:
a-b

array([-1.36515899,  0.71965918, -1.58327163, -1.2451748 ,  2.36259728,
        3.46841191,  1.00289403,  0.05536372, -0.99171522, -0.58008654])

In [29]:
3*a*b

array([ 1.50892405e+00,  4.27008989e+00, -9.99599883e-01, -1.16162882e+00,
        3.49408376e+00, -6.66416521e+00, -5.99554235e-01, -1.42447889e-03,
        6.32546579e-01, -1.79362403e-01])

In [30]:
1/a

array([-0.59991554, -1.12828528, -0.74997347, -1.65988533, -2.38805006,
        0.38156018,  3.64569998, 22.3443549 ,  5.55692321, -2.24190869])

In [31]:
a>0

array([False, False, False, False, False,  True,  True,  True,  True,
       False])

In [35]:
a==0.38156018

array([False, False, False, False, False, False, False, False, False,
       False])

In [34]:
a>0

array([False, False, False, False, False,  True,  True,  True,  True,
       False])

In [36]:
a[a>0]

array([2.62081855, 0.27429575, 0.04475403, 0.1799557 ])